apiVersion: batch/v1
kind: Job
metadata:
  name: exp-svm-semg-39
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: cpu-container
          image: gitlab-registry.nrp-nautilus.io/yg5d6/cptdeeplearning:semg
          command: ["/bin/bash", "-c"]
          args:
            - wandb login d7f81da19c5965b1c5eff37a677caab3ffb5379c; git clone https://github.com/jacketdembys/confounding_mitigation.git; cd confounding_mitigation; mv ../data .; WANDB=1 GROUP=SVM-sEMG python3 src/sEMG_GA-SVM.py -s 39 -nsub 1 -ngen 8 -pop 128 -perm 1000 -thread 16;
          resources:
            limits:
              memory: "16G"
              cpu: "16"
            requests:
              memory: "16G"
              cpu: "16"
      restartPolicy: Never