apiVersion: v1
kind: Pod
metadata: 
    name: exp-svm-semg-39
spec:
  containers:
  - name: cpu-container
    image: gitlab-registry.nrp-nautilus.io/yg5d6/cptdeeplearning:semg
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: 16
      requests:
        memory: 16Gi
        cpu: 16